put http://localhost:3001/violators/testid
Content-Type: application/json

{
    "firstName": "test",
    "lastName": "test",
    "serialNumber": "testid",
    "violationTime": 52438159876,
    "closestViolation": 491808
}