name: Build & Fly Deploy

on:
  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: build & copy frontend & deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install frontend dependencies
        run: |
          npm install
        working-directory: ./frontend
      - name: Build frontend, copy it to backend and deploy to fly.io
        run: |
          npm run build:ui
          flyctl deploy --remote-only
        working-directory: ./backend
